### ISSUE TITLE
Mention your fork in original repo issue

### ISSUE THREAD

**Issue by qweered** [rcalixte/awesome-wayland#1]

**Comment by rcalixte** [comment]
I'm not sure I fully understand. The original repository is archived which means no additional Issues can be opened for it. I'm also more focused on filling in the contents right now. I'm glad if others find it to be helpful in the meanwhile too.

**Comment by qweered** [comment]
So people can find your repo when they open issues tab in original repo, right now its almost impossible to find your fork

**Comment by rcalixte** [comment]
> So people can find your repo when they open issues tab in original repo

On GitHub, there is no way to open an Issue on a repository that is archived. The original repository is archived.



> right now its almost impossible to find your fork

I still have additional things I want to add/change here so my focus isn't necessarily on attention. As I said before, I'm glad if others find it to be helpful as it currently is. If @natpen wants to add a notice on the original repository, that would be fine. I just want to make sure that expectations on my end are established beforehand.
