### ISSUE TITLE
Remove the forked levee

### ISSUE THREAD

**Issue by Ashvith10** [rcalixte/awesome-wayland#24]
~~The original project by nmeum, called levee has been renamed to creek (nmeum/levee redirects to nmeum/creek). The fork on SoureHat however, retains the original name.~~

levee's fork on GitHub was renamed to creek. This makes it a duplicate entry.

**Comment by rcalixte** [comment]
@Ashvith10 Thank you for the report. Are you sure about the connection of these projects? Creek is a fork of levee. It is possible that the repository was forked and then renamed as that would explain the redirect. Looking at the recent commit history of both projects, there are different authors and similar updates done at different times; both projects updated to Zig 0.13.0 independently months apart from each other.

At this point, there are three projects with ties to levee listed here and each also appears to be at least somewhat maintained by separate developers.

**Comment by Ashvith10** [comment]
@rcalixte my mistake, it should be the other way round - the fork seems to be redirecting to creek. The original one is still maintained on SourceHut.

**Comment by rcalixte** [comment]
> @rcalixte my mistake, it should be the other way round - the fork seems to be redirecting to creek. The original one is still maintained on SourceHut.

Ah, I see now. Thank you! It's been fixed.
