### ISSUE TITLE
Add Hidamari and Hanabi in the wallpaper category.

### ISSUE THREAD

**Issue by sheesh3178** [rcalixte/awesome-wayland#30]
Both are made by the same dev. They display animated wallpaper.

If they're not good enough then don't add. I think it's pretty underrated and no one's mentioning it at all.

**Comment by rcalixte** [comment]
Thank you for the interest! Unfortunately, neither of these projects meet the criteria for inclusion.

**Comment by sheesh3178** [comment]
That's unfortunate. What is the criteria anyway?

**Comment by rcalixte** [comment]
> What is the criteria anyway?

This is covered in the README, highlighted under [here](https://github.com/rcalixte/awesome-wayland?tab=readme-ov-file#scope).

**Comment by sheesh3178** [comment]
Yeah, they both support Wayland natively and are actively maintained.
What's suppose to be the problem? (well maybe Hanabi is specifically made
for GNOME but it's still Wayland)

**Comment by rcalixte** [comment]
> Yeah, they both support Wayland natively and are actively maintained. What's suppose to be the problem? (well maybe Hanabi is specifically made for GNOME but it's still Wayland)

> **designed** to support the Wayland ecosystem

Neither of these were **designed** for Wayland. That text is intentionally in bold.
