### ISSUE TITLE
please include `pinnacle`

### ISSUE THREAD

**Issue by sga-13** [rcalixte/awesome-wayland#36]
[pinnacle](https://github.com/pinnacle-comp/pinnacle) is a wayland compositor

**Comment by rcalixte** [comment]
It should be noted that I am trying to avoid projects that are heavily WIP until they are a bit more mature. There is no guarantee that these will ever reach maturity either. In addition, at some point in the future, I am planning to address the unmaintained or incomplete projects but I haven't formulated the details for that yet.
